name: Deploy app on Azure
on:
  #push:
  #  branches:
  #    - aubinaso
   workflow_dispatch:
   
jobs:
 build:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_SECRET }}
      APP_NAME: "svelte_webapp"
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node_version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Run Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          creds: ${{ env.AZURE_CREDENTIALS }}
   
