name: Deploy Wikismiley on Azure App Services 📨

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checks out repo's code 📥
      uses: actions/checkout@v3

    - name: Sets up Node.js 🏗️
      uses: actions/setup-node@v3
      with:
        node-version: 18 

    - name: Installs dependencies ⬇️
      run: npm ci

    - name: Builds the Svelte app ⚒️
      run: npm run build --if-present

    - name: Save build artifacts 💾
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checks out repo's code 📥
      uses: actions/checkout@v3